# Generated by Django 2.2.16 on 2022-11-04 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_comment_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='atuhor',
            new_name='author',
        ),
    ]
